### ISSUE TITLE
Dont give Backpack on join

### ISSUE THREAD

**Issue by RelaxoGIT** [GeorgH93/Minepacks#180]
How do I disable that everyone gets the backpack when they join? I want it to be only accesible through the command

**Comment by GeorgH93** [comment]
Change the `ItemShortcut.Enabled` option to false like this:


```yaml
# Gives the players an item they can interact with to open their backpack. Only works on MC 1.8 or newer.
ItemShortcut:
  # If enabled the players will be given an item they can interact with to open the backpack.
  # The item may not be removed from their inventory as long as this option is enabled.
Enabled: false
```
