### ISSUE TITLE
How do i make it where the backpack doesnt spawn in inventory for default

### ISSUE THREAD

**Issue by ToxicWaterOP** [GeorgH93/Minepacks#256]
How do i make it where the backpack doesnt spawn in inventory for default?

**Comment by GeorgH93** [comment]
You can disable the item entirely by disabling the ItemShortcut, but this will completely disable it.
```yaml
# Gives the players an item they can interact with to open their backpack. Only works on MC 1.8 or newer.
ItemShortcut:
  # If enabled the players will be given an item they can interact with to open the backpack.
  # The item may not be removed from their inventory as long as this option is enabled.
  Enabled: false
```

There currently is no option to give the item only on demand.
