### ISSUE TITLE
World filter is not working

### ISSUE THREAD

**Issue by emerysteele** [GeorgH93/Minepacks#288]
```

WorldSettings:
  # Options: blacklist (all worlds listed in FilteredWorlds will be blocked), whitelist (all worlds listed in FilteredWorlds will be allowed)
  FilterType: "whitelist"
  # All worlds listed here will not have the plugin usable
  # FilteredWorlds: ["creative_world"]
  # FilteredWorlds: ["creative_world1", "creative_world2"]
  FilteredWorlds: ["world"]
  # Defines how the Blacklist will be enforced
  # Options:
  #   Message           = The player will see a message that the usage of the backpack is not allowed in this world.
  #   MissingPermission = The player will receive the plugins no permission message.
  #   NoPlugin          = The plugin will not be available at all and act as if it was not installed.
  #                       This also exclude players with permission to bypass the world restriction from using it!
  #                       It will not disable the Shulkerboxes filter!
  BlockMode: "Message"

```

### Details
**Description**  
This config should only let minepacks work in world named "world"

**Steps to reproduce**  
1. Set config
2. Restarted server
3. Minepacks works in all worlds, not just world "world"

**Expected behavior**  
Minepacks should only work in world "world"
