### ISSUE TITLE
How to use the Plugin without Permissions System.

### ISSUE THREAD

**Issue by Falseee** [GeorgH93/Minepacks#6]
How to use the Plugin without Permissions System.
I just want to use this Plugin.

**Comment by GeorgH93** [comment]
You can use the permissions.yml (next to your bukkit/spigot jar file) file.

```
server.basics:
  default: true
  children:
    backpack: true
    backpack.size.6: true
```
