### ISSUE TITLE
Unable to connect when MySQL password contains "#"

### ISSUE THREAD

**Issue by ethernetcat** [GeorgH93/Minepacks#77]
### Information
**Environment information**
*Plugin + server version info*:
Minepacks 2.3.4
paper 135

*Online mode*: false
*BungeeCord*: yes

**Plugin config (optional)**
```
Database:
  SQL:
    Host: localhost:3306
    Database: Minepacks
    User: root
    Password: P@SS#WORD     # "P@SS#WORD" or 'P@SS#WORD'
```

### Details
**Description**  
If the password contains "#", the password will not be read correctly.
To avoid this, enclose it in double quotes or quotes.
But it will be removed when Minepacks is updated and the config version is changed.

**Steps to reproduce**  
Include "#" in password

**Expected behavior**  
Values ​​enclosed in double quotes or quotation marks in the config will be enclosed again in the config update
